name: "Deploy to Firebase"

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4.1.6

      - name: "Deploy"
        uses: w9jds/firebase-action@v13.9.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
